# Generated by Django 3.2.16 on 2023-07-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T_User',
            fields=[
                ('U_Id', models.AutoField(primary_key=True, serialize=False)),
                ('U_FirstName', models.CharField(max_length=150)),
                ('U_LastName', models.CharField(max_length=150)),
                ('U_Email', models.EmailField(max_length=254)),
                ('U_Pwd', models.CharField(max_length=150)),
                ('U_Admin', models.BooleanField()),
                ('U_Client', models.BooleanField()),
            ],
        ),
    ]
