# Generated by Django 3.2.16 on 2023-06-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_image', models.CharField(max_length=200)),
                ('link_image', models.CharField(max_length=200)),
                ('description_image', models.TextField()),
            ],
        ),
    ]
