# Generated by Django 3.2.16 on 2023-07-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=200)),
                ('images', models.CharField(max_length=200)),
                ('descriptions', models.CharField(max_length=200)),
                ('ingredients', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('prices', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=200)),
                ('Link', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
