# Generated by Django 4.2.2 on 2023-08-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0004_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='descriptions',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='products',
            name='ingredients',
            field=models.CharField(max_length=2000),
        ),
    ]
